name: Unit test - Pokemon SV Damage Calculator

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# Allow the job to fetch a GitHub ID token
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  Check-pytest-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 2.1.3

      - name: Install Dependencies
        run: |
          poetry env use python3.12
          poetry install --no-interaction

      - name: Pytest Unit Test
        run: |
          set -o pipefail
          poetry run pytest ./tests -v --cov=./ --cov-report=term-missing --junitxml=pytest.xml | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./tests/pytest-coverage.txt
          junitxml-path: ./tests/pytest.xml
          create-new-comment: false
